platform :ios, '8.0'

project 'CPEDataExample'
workspace 'CPEDataExampleWorkspace'
use_frameworks!

target 'CPEDataExample' do
    
    pod 'CPEData', :path => '../'
    pod 'RETableViewManager'

end
